Document: iin
Title: Debian iin Manual
Author: <insert document author here>
Abstract: This manual describes what iin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iin/iin.sgml.gz

Format: postscript
Files: /usr/share/doc/iin/iin.ps.gz

Format: text
Files: /usr/share/doc/iin/iin.text.gz

Format: HTML
Index: /usr/share/doc/iin/html/index.html
Files: /usr/share/doc/iin/html/*.html


